### ISSUE TITLE
Tracking issue: react-ification

### ISSUE THREAD

**Issue by nrc** [nrc/rustw#128]
Convert to using React

- [x] Errors and build results
- [x] error explanations
- [x] build animation
- [x] buttons/menus/search box in top bar
- [x] menus
- [x] breadcrumbs
- [x] source view (including highlights)
- [x] directory view
- [x] search results (search and find)
- [x] summary/docs
- [ ] history/state/back button use/return to build results
- [ ] URLs
- [ ] improve workflow (e.g., #126)
- [ ] ~~optimise (seems to be dog slow atm)~~

**Comment by nrc** [comment]
Refactorings for when initial work is done:
* move some exports from rustw.js to utils.js
* split components into presentational and container kinds
* general tidying up/factoring out common functionality
* smaller components - e.g., overlay for menu, etc.

**Comment by AlexPikalov** [comment]
@nrc any plans to rid of jquery?

Maybe I'm missing something, but as far as I can see it's used just for DOM manipulations + ajax call. DOM manipulations should be done by React. As for ajax calls, for me it makes sense to use some of [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) polyfills such as https://github.com/matthew-andrews/isomorphic-fetch. Which is pretty wide used in React applications.

Also I didn't found any other dependencies you use which would depends on jquery.

**Comment by nrc** [comment]
> any plans to rid of jquery?

I would like to do this, and I've been removing bits as I go, but it has not been high priority. It would be great to remove the dependency. I'm not sure what is left, I don't think there are that many DOM interactions, and probably nothing that can't be replaced with native equivalents or React. I'd be happy to use fetch natively - I don't think we need to accommodate people on older browsers. Alternatively, we could use XMLHttpRequest - I don't think it is much harder than `$ajax` (I would like to avoid adding another dep).
