### ISSUE TITLE
rustw roadmap

### ISSUE THREAD

**Issue by nrc** [nrc/rustw#150]
See https://github.com/nrc/rustw/blob/master/design.md for some discussion of options.

This is mostly a high-level strawman/sketch and is open to iteration/improvement.

I plan to focus on these two goals:
* rustw as a code browser embedded in rustdoc (primarily server-hosted)
* rustw as a standalone code browser (primarily run locally, but possible to be server-hosted), `cargo src`

Secondary goal:
* web based build tool for Rust

By secondary goal, I mean that I'd like it to happen, and will try to keep it working, but won't be putting much energy into it.

Some development sub-goals/guiding principles:
* focus on code search and exploration
* primary use case is reading code (c.f., debugging). Possible user stories:
  - getting to know a code base
  - chasing control flow when debugging
  - help when refactoring
  - understanding the API of a library (in conjunction with documentation)

And some concrete 'goals':
- [x] separate binary for code browsing without building
- [x] `cargo src` Cargo plugin
- [ ] navigation for browsing - URLs, back button, breadcrumbs
- [x] update the top bar to be browsing focussed (maybe don't have a top bar at all)
- [ ] local performance (time from starting a build to browsing, latency rendering a page)
- [ ] network performance (experience using rustw with remote server)
