### ISSUE TITLE
Tracking issue: awesome remote experience

### ISSUE THREAD

**Issue by nrc** [nrc/rustw#95]
Primarily speed and security issues (cc #13)
- [ ] inlining build step for JS, CSS, libs, etc.
- [ ] [render handlebars stuff on the server-side](https://github.com/nrc/rustw/issues/90)
- [ ] minimise number of messages sent back and forth
- [ ] [build from VFS](https://github.com/nrc/rustw/issues/89) because avoid disk access
- [ ] security audit
- [ ] sandboxing
- [ ] prevent deps indexing from allowing access to whole disk (unclear how deps and VFS will even work together)
- [ ] minimise size of messages
