### ISSUE TITLE
Tracking issue: awesome build experience

### ISSUE THREAD

**Issue by nrc** [nrc/rustw#98]
Two elements - rustw as usable as cargo/rustc on the command line (at least for simple tasks), and make use of the web UI for doing cool stuff with errors, in particular, explaining tricky errors to users.
- [ ] multirust #6 
- [ ] borrow check errors #7 
- [ ] incrementally show errors #9 
- [ ] apply suggestion #15 
- [ ] cancel build #16 
- [ ] cargo test/display test output #66 
- [ ] -Zno-trans #79
